### PR TITLE
Preserve tag case

### LINKED ISSUE #4: BUG 🐛: `<Footer>` gets rewritten to `<footer>` + all other case insensitive html tag collisions
When an imported component has a tag reference name that collides with one of the standard tag names in HTML - like for instance \<Footer /> - the plugin resets it to \<footer />. Thus being lowercase then it won't get rendered by astro and the component is missing in the output.

I don't like the clunkiness of having to keep a complete nomenclature in mind to avoid collisions like these.

Also the compiler doesn't complain - how could it be aware? - so the then missing component gets dropped silently.

### PR DESCRIPTION
**Pull request by antonyfaris**
Fixes #4
While fixing this I encounter an error with the test "with-script", so I also fix that.

### CODE REVIEW

**Review by jasikpark — APPROVED** [review]
lgtm! thanks for the pr - i'll approve running CI and merge when it passes!

**Comment by jasikpark** [comment]
Pulled it down and tested locally - looks good! Hopefully my changes to the workflow in main will fix ci for the future

**Comment by bobaekang** [comment]
@jasikpark I'm experiencing the same issue that this PR fixes. When can we expect a new release that includes this PR? Thank you in advance for your work 🙏

**Comment by jasikpark** [comment]
>  @jasikpark I'm experiencing the same issue that this PR fixes. When can we expect a new release that includes this PR? Thank you in advance for your work 🙏 

released! 🚀

**Pull request merged**
